// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:imart/app/core/storage/hive/adapters/address.dart';
import 'package:imart/app/core/storage/hive/adapters/delivery_tracking.dart';
import 'package:imart/app/core/storage/hive/adapters/user.dart';
import 'package:imart/features/product_details/infrastructure/data_sources/local/product_detail_cache.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AddressModelAdapter());
    registerAdapter(DeliveryTrackingDataAdapter());
    registerAdapter(ProductMetadataAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AddressModelAdapter());
    registerAdapter(DeliveryTrackingDataAdapter());
    registerAdapter(ProductMetadataAdapter());
    registerAdapter(UserModelAdapter());
  }
}
